export const REQUEST_DATA_PENDING = 'REQUEST_DATA_PENDING';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILED = 'REQUEST_DATA_FAILED';
export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const ON_SEARCH_CHANGE_FILTER_RESULTS = 'ON_SEARCH_CHANGE_FILTER_RESULTS';
export const ON_SEARCH_CHANGE_FILTER_NULL = 'ON_SEARCH_CHANGE_FILTER_NULL';
export const SORT_DATA = 'SORT_DATA';